# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneof.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneof.proto',
  package='oneof',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0boneof.proto\x12\x05oneof\"\x14\n\x03REQ\x12\r\n\x05\x66name\x18\x01 \x02(\t\"i\n\x05\x41tivo\x12\x0e\n\x04nome\x18\x05 \x01(\tH\x00\x12\r\n\x03\x63od\x18\x06 \x01(\x05H\x00\x12\x19\n\x03req\x18\x07 \x01(\x0b\x32\n.oneof.REQH\x00\x12\r\n\x05valor\x18\x03 \x02(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\x42\x04\n\x02id\"H\n\rSampleMessage\x12\x0e\n\x04name\x18\x04 \x01(\tH\x00\x12\x19\n\x03rrq\x18\t \x01(\x0b\x32\n.oneof.REQH\x00\x42\x0c\n\ntest_oneof'
)




_REQ = _descriptor.Descriptor(
  name='REQ',
  full_name='oneof.REQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fname', full_name='oneof.REQ.fname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=42,
)


_ATIVO = _descriptor.Descriptor(
  name='Ativo',
  full_name='oneof.Ativo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='oneof.Ativo.nome', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cod', full_name='oneof.Ativo.cod', index=1,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='req', full_name='oneof.Ativo.req', index=2,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valor', full_name='oneof.Ativo.valor', index=3,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='oneof.Ativo.timestamp', index=4,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='id', full_name='oneof.Ativo.id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=44,
  serialized_end=149,
)


_SAMPLEMESSAGE = _descriptor.Descriptor(
  name='SampleMessage',
  full_name='oneof.SampleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='oneof.SampleMessage.name', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rrq', full_name='oneof.SampleMessage.rrq', index=1,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='test_oneof', full_name='oneof.SampleMessage.test_oneof',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=151,
  serialized_end=223,
)

_ATIVO.fields_by_name['req'].message_type = _REQ
_ATIVO.oneofs_by_name['id'].fields.append(
  _ATIVO.fields_by_name['nome'])
_ATIVO.fields_by_name['nome'].containing_oneof = _ATIVO.oneofs_by_name['id']
_ATIVO.oneofs_by_name['id'].fields.append(
  _ATIVO.fields_by_name['cod'])
_ATIVO.fields_by_name['cod'].containing_oneof = _ATIVO.oneofs_by_name['id']
_ATIVO.oneofs_by_name['id'].fields.append(
  _ATIVO.fields_by_name['req'])
_ATIVO.fields_by_name['req'].containing_oneof = _ATIVO.oneofs_by_name['id']
_SAMPLEMESSAGE.fields_by_name['rrq'].message_type = _REQ
_SAMPLEMESSAGE.oneofs_by_name['test_oneof'].fields.append(
  _SAMPLEMESSAGE.fields_by_name['name'])
_SAMPLEMESSAGE.fields_by_name['name'].containing_oneof = _SAMPLEMESSAGE.oneofs_by_name['test_oneof']
_SAMPLEMESSAGE.oneofs_by_name['test_oneof'].fields.append(
  _SAMPLEMESSAGE.fields_by_name['rrq'])
_SAMPLEMESSAGE.fields_by_name['rrq'].containing_oneof = _SAMPLEMESSAGE.oneofs_by_name['test_oneof']
DESCRIPTOR.message_types_by_name['REQ'] = _REQ
DESCRIPTOR.message_types_by_name['Ativo'] = _ATIVO
DESCRIPTOR.message_types_by_name['SampleMessage'] = _SAMPLEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

REQ = _reflection.GeneratedProtocolMessageType('REQ', (_message.Message,), {
  'DESCRIPTOR' : _REQ,
  '__module__' : 'oneof_pb2'
  # @@protoc_insertion_point(class_scope:oneof.REQ)
  })
_sym_db.RegisterMessage(REQ)

Ativo = _reflection.GeneratedProtocolMessageType('Ativo', (_message.Message,), {
  'DESCRIPTOR' : _ATIVO,
  '__module__' : 'oneof_pb2'
  # @@protoc_insertion_point(class_scope:oneof.Ativo)
  })
_sym_db.RegisterMessage(Ativo)

SampleMessage = _reflection.GeneratedProtocolMessageType('SampleMessage', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEMESSAGE,
  '__module__' : 'oneof_pb2'
  # @@protoc_insertion_point(class_scope:oneof.SampleMessage)
  })
_sym_db.RegisterMessage(SampleMessage)


# @@protoc_insertion_point(module_scope)
